In [ ]:
import pandas as pd
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=['A','B','C'],index=['x','y','z'])
df.head(2)
df.tail()

   A  B  C
x  1  2  3
y  4  5  6

for index

In [17]:
df.index

Index(['x', 'y', 'z'], dtype='str')

for columns

In [18]:
df.columns

Index(['A', 'B', 'C'], dtype='str')

for the index names

In [19]:
df.index.tolist()

['x', 'y', 'z']

for more info about df

In [13]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

tell meaningful info about data

In [14]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [16]:
df['A'].unique()

array([1, 4, 7])

In [20]:
df.shape

(3, 3)

In [21]:
df.size

9